/*
 * This source file was generated by the Gradle 'init' task
 */
package com.chess;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.print("Please provide comma separated value for piece and block (e.g. Pawn,G7):");
        Scanner in = new Scanner(System.in);
        String input = in.nextLine();
        try {
            String inputs[] = input.split(",");
            String pieceName = inputs[0];
            String block = inputs[1];
            showPossibleMoves(pieceName, block);
        }catch (Exception e) {
            System.err.println("Please provide valid input");
        }
    }

    public static void showPossibleMoves(String pieceName, String block) {
        System.out.printf("Possible moves for %s at %s block are: ", pieceName, block);
        //TODO
        /* calculating and printing possible moves will add here later on */
    }
}
