/*
 * This source file was generated by the Gradle 'init' task
 */
package com.chess;


import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class AppTest {
    @Test
    public void testApp() {
        App classUnderTest = new App();
        assertTrue(true);
    }
}
